services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=task_planner
    ports:
      - 3305:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql # Persist data
  my-node-app:
    restart: on-failure
    build: .
    ports:
      - 5050:5030
    environment:
      - PORT=5030
      - DB_USERNAME=root
      - DB_PASSWORD=root1234
      - DB_NAME=task_planner
      - NODE_ENV=dev
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: