name: test-express-docker

on: workflow_dispatch

jobs: 
  test:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0'
    - name: Build the Docker images
      run: docker-compose build
    - name: Run the docker compose
      run: docker-compose up -d
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1
      with:
        mysql version: '8'
        root password: ${{ secrets.DB_PASSWORD }}

    - name: Run database migration
      run: |
        mysql -h 127.0.0.1 -u root -p${{ secrets.DB_PASSWORD }} -e "
          GRANT ALL PRIVILEGES ON your_database.* TO '${{ secrets.DB_USERNAME }}'@'%' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';
          FLUSH PRIVILEGES;
        "
    - name: Install Dependencies
      run: npm i
    - name: Run tests
      env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_NAME: test_task
          PORT: 5030
      run: npm run test
    - name: finish docker down
      run: docker-compose down

