name: test-express-docker

on: workflow_dispatch

jobs: 
  test:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0'
    - name: Build the Docker images
      run: docker-compose build
    - name: Run the docker compose
      run: docker-compose up -d
    - name: Install Dependencies
      run: npm i
    - name: Run tests
      env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_NAME: test_task
          PORT: 5030
      run: npm run test
    - name: finish docker down
      run: docker-compose down

