on: workflow_dispatch

jobs: 
  test:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0'

    - name: Check Running containers
      run: docker ps
        
    - name: Build the Docker images
      run: docker-compose build
      
    - name: Run the docker compose
      run: docker-compose up -d
      
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
          host port: 3306
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql database: 'testdb'
          mysql root password: ${{ secrets.DB_PASSWORD }}

    - name: Check MySQL health
      run: |
        until mysqladmin ping -h 127.0.0.1 -u root -p${{ secrets.DB_PASSWORD }}; do
        sleep 1
        done
        
    - name: Run database migration
      run: |
        mysql -h 127.0.0.1 -u root -p${{ secrets.DB_PASSWORD }} -e "
          GRANT ALL PRIVILEGES ON your_database.* TO '${{ secrets.DB_USERNAME }}'@'%' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';
          FLUSH PRIVILEGES;
        "
    - name: Install Dependencies
      run: npm i
      
    - name: Run tests
      env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_NAME: test_task
          PORT: 5030
      run: npm run test
      
    - name: finish docker down
      run: docker-compose down
